services:
  micro-challenger:
    image: micro-challenger
    volumes:
      - ./data:/data
    ports:
      - 8866:8866
    command: ["0.0.0.0:8866", "/data"]
  jobmanager:
    image: flink:2.0-java17
    hostname: jobmanager
    container_name: jobmanager
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager        
  taskmanager:
    image: flink:2.0-java17
    depends_on:
      - jobmanager
    hostname: taskmanager
    container_name: taskmanager
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
    volumes:
      - ./Results:/opt/flink/output